# Create eC2 instances and install secured web server with hello world page"

- name: Launch instance
  ec2:
    ec2_access_key: "{{ aws_access_key }}"
    ec2_secret_key: "{{ aws_secret_key }}"
    keypair: "test123"
    instance_type: "t2.micro"
    user_data: "{{ lookup('file', 'user_data.sh') }}"
    image: "{{ aws_image }}"
    wait: true
    id: "{{ 1000 |random}}"
    group: "{{ aws_project_name }} Security Group"
    region: "{{ aws_region }}"
    vpc_subnet_id: "{{ aws_public_subnet_id }}"
    assign_public_ip: yes
    count: "1"
  register: aws_ec2
  
- name: html file to the destination file
  copy:
    src: html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644


