
# this file is to install prerequistes needed to spin up ec2 on Aws
---
- easy_install:
    name: pip
    state: latest

- pip:
    name: "{{ item }}"
  with_items:
    - boto
    - botocore
    - boto3

